//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoTradeLap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankTransferHistory
    {
        public int id { get; set; }
        public System.DateTime created { get; set; }
        public int user_id { get; set; }
        public decimal amount { get; set; }
        public string currency { get; set; }
    
        public virtual User User { get; set; }
    }
}
